#!/usr/bin/env node
/**
 * CineLink OTA Update Pusher
 * ──────────────────────────
 * Updates src/config/updateInfo.js with the new changelog, then
 * pushes an OTA update to EAS so everything stays in sync.
 *
 * Usage:
 *   node push-update.js "Your short message" "- Change 1\n- Change 2"
 *
 * Examples:
 *   node push-update.js "Fix search crash and improve UI"
 *   node push-update.js "New dark mode colors" "- Richer dark palette\n- Better contrast"
 *
 * The message and changelog are embedded into the JS bundle itself, so
 * the Settings screen always shows the correct info for the installed
 * version — no more hardcoding in app.config.js.
 */

const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

// ── Args ──────────────────────────────────────────────────────────────────────
const args = process.argv.slice(2);
if (args.length === 0) {
  console.error(
    '❌  Usage: node push-update.js "Your message" "optional changelog"',
  );
  process.exit(1);
}

const message = args[0].trim();
const changelog = args[1] ? args[1].trim() : message;

// ── Read current version from app.config.js ───────────────────────────────────
let version = "2.0.0";
try {
  // app.config.js exports a function — eval a cheap regex instead of requiring it
  const appConfigText = fs.readFileSync(
    path.join(__dirname, "app.config.js"),
    "utf8",
  );
  const match = appConfigText.match(/version:\s*["']([^"']+)["']/);
  if (match) version = match[1];
} catch (_) {}

const pushedAt = new Date().toISOString();

// ── Update src/config/updateInfo.js ───────────────────────────────────────────
const updateInfoPath = path.join(__dirname, "src", "config", "updateInfo.js");

// Escape strings for safe embedding
const escape = (s) =>
  s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

const newContent = `/**
 * Current OTA update metadata.
 * This file is automatically updated by \`node push-update.js\` before each
 * OTA push, so it is always accurate — it ships inside the JS bundle itself.
 *
 * DO NOT edit this file manually. Use:
 *   node push-update.js "Your message" "- Change 1\\n- Change 2"
 */

const updateInfo = {
  message: "${message.replace(/"/g, '\\"')}",
  description: "${message.replace(/"/g, '\\"')}",
  changelog: "${changelog.replace(/"/g, '\\"')}",
  version: "${version}",
  pushedAt: "${pushedAt}",
};

export default updateInfo;
`;

fs.writeFileSync(updateInfoPath, newContent, "utf8");
console.log(`✅ Updated src/config/updateInfo.js`);
console.log(`   Message  : ${message}`);
console.log(`   Changelog: ${changelog}`);
console.log(`   Version  : ${version}`);
console.log(`   Pushed at: ${pushedAt}`);
console.log();

// ── Push OTA ──────────────────────────────────────────────────────────────────
const easCmd = `npx eas update --branch preview --message "${message.replace(/"/g, '\\"')}" --non-interactive`;
console.log(`🚀 Running: ${easCmd}`);
console.log();

try {
  execSync(easCmd, { stdio: "inherit", cwd: __dirname });
  console.log();
  console.log("✅ OTA update pushed successfully!");
} catch (err) {
  console.error("❌ EAS update failed:", err.message);
  process.exit(1);
}
