/**
 * Current OTA update metadata.
 * This file is automatically updated by `node push-update.js` before each
 * OTA push, so it is always accurate — it ships inside the JS bundle itself.
 *
 * DO NOT edit this file manually. Use:
 *   node push-update.js "Your message" "- Change 1\n- Change 2"
 */

const updateInfo = {
  message: "Add gamification to watchlists - XP, levels, streaks, achievements",
  description: "Complete gamification system for watchlists",
  changelog:
    "- XP & 8 levels (Newbie → Legend)\n- Watch streaks with daily bonuses\n- 12 unlockable achievements\n- XP toast on movie watched\n- List completion celebration",
  version: "2.0.0",
  pushedAt: "2026-03-06T00:00:00.000Z",
};

export default updateInfo;
