/**
 * Current OTA update metadata.
 * This file is automatically updated by `node push-update.js` before each
 * OTA push, so it is always accurate — it ships inside the JS bundle itself.
 *
 * DO NOT edit this file manually. Use:
 *   node push-update.js "Your message" "- Change 1\n- Change 2"
 */

const updateInfo = {
  message: "Gamification v5 - badge icons + details",
  description: "Gamification v5 - badge icons + details",
  changelog: "All 20 badges now use contextual Ionicons instead of emojis; tap any badge to open a detail panel showing its title, description, earn criteria, and locked/unlocked status",
  version: "2.0.0",
  pushedAt: "2026-03-08T07:47:29.469Z",
};

export default updateInfo;
