/**
 * Current OTA update metadata.
 * This file is automatically updated by `node push-update.js` before each
 * OTA push, so it is always accurate — it ships inside the JS bundle itself.
 *
 * DO NOT edit this file manually. Use:
 *   node push-update.js "Your message" "- Change 1\n- Change 2"
 */

const updateInfo = {
  message: "Gamification v7 - cloud-only storage",
  description: "Gamification v7 - cloud-only storage",
  changelog: "Removed AsyncStorage for gamification. All XP reads and writes go directly to backend/Firestore - no local storage, no merge complexity, no race conditions.",
  version: "2.0.0",
  pushedAt: "2026-03-08T14:50:24.077Z",
};

export default updateInfo;
